# Generated by Django 4.2.2 on 2023-06-11 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('discription', models.TextField(blank=True, null=True)),
                ('pricd', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
